### ISSUE TITLE
در خواست تایید DnsLab-CLI

### ISSUE THREAD

**Issue by NoobforAl** [AkbarAsghari/DNSLab-WebSite#22]
سلام،
من این [CLI](https://github.com/NoobforAl/DnsLab-CLI) رو برای  DNS lab نوشتم، تقریبا برای تمامی سیستم هایی که Go دارن جواب گو هست.
می خواستم بدونم این cli اوکی هست یا که نه!

**Comment by AkbarAsghari** [comment]
با سلام 
حتما بررسی میکنم و خدمتتون اعلام میکنم 
ممنون بابت کار با ارزشتون

**Comment by AkbarAsghari** [comment]
مهندس بررسی کردم فکر میکنم در اکثر متد ها api.dnslab.ir/ip رو بصورت پیش فرض فراخوانی میکنید این رو بردارید

**Comment by NoobforAl** [comment]
فیکس شد!
