### ISSUE TITLE
Ping Bug

### ISSUE THREAD

**Issue by NoobforAl** [AkbarAsghari/DNSLab-WebSite#28]
sometimes get bad response for not valid host name !

for example : 

![Screenshot 2023-01-20 193446](https://user-images.githubusercontent.com/58856931/213748550-1c7af9b6-8dc2-49d6-871c-5ed4ac9075ae.png)

**Comment by AkbarAsghari** [comment]
Hi 
Thanks for report i will check this and response as soon

**Comment by AkbarAsghari** [comment]
![ddddd](https://user-images.githubusercontent.com/36479679/214118180-75008bd1-ab89-4ccd-bd3c-9556234a72ad.png)

با سلام 
بررسی شد در سیستم خونه (لوکال) هیچ چیزی پیدا نمیشد 
اما در سرور شرکت یه آی پی بر میگردونه که این آی پی متعلق به شرکت AKAMAI هستش که در زمینه امنیت فعالیت میکنند احتمالی که میدم اینه که هاست که میزبان سایت هست (پارس پک) توسط این شرکت یعنی Akamai در آمریکا امنیتش برقرار میشه که همین امر موجب میشه دامنه های اشتباه به آی پی آن ها اشاره کند .
اما این موضوع رو حتما با پارس پک بررسی فنی خواهم کرد .
ممنون از حسن نیت شما 
تصویر بالا هم پینگ از یه دامنه اشتباه در سرور سایت هستش
