### ISSUE TITLE
اضافه کردن ورژن به برنامه

### ISSUE THREAD

**Issue by NoobforAl** [AkbarAsghari/DNSLab-WebSite#31]
امکان اضافه کردن تگ به برنامه وجود داره ؟
برای مثال اگر امکانش هست برنامه فعلی رو روی ورژن 1.0.0 گذاشته شه و هر تغیری بش اضافه شد ورژن تغیر کنه و اضافه شه.
این طوری هم تغیرات مشخص میشه و توسعه کمی اسون تر.

**Comment by AkbarAsghari** [comment]
به زودی تمام API های سایت بصورت Swagger در دسترس عموم قرار میدم
